//! Links the vendored libmpv (see docs/BUILD.md) via its pkg-config file, and adds
//! an rpath so `cargo test -p player` (and any other binary linking this
//! crate) finds `libmpv.dylib` at runtime without exporting
//! `DYLD_LIBRARY_PATH` by hand.
//!
//! We don't ask pkg-config for `--cflags`/use its include path: `src/sys.rs`
//! is a hand-written `extern` block (see its doc comment for why), not
//! generated by `bindgen` against the vendored headers, so this build script
//! only needs to resolve linker flags.

use std::env;
use std::path::PathBuf;

fn main() {
    let manifest_dir = PathBuf::from(
        env::var("CARGO_MANIFEST_DIR").expect("cargo always sets CARGO_MANIFEST_DIR"),
    );
    // crates/player -> repo root is two directories up.
    let repo_root = manifest_dir
        .parent()
        .and_then(|p| p.parent())
        .expect("crates/player is nested two directories under the workspace root");
    let vendor_lib = repo_root.join("vendor").join("prefix").join("lib");
    let pkgconfig_dir = vendor_lib.join("pkgconfig");

    // Point pkg-config at the vendored libmpv build instead of any
    // system/Homebrew mpv, so dev and CI always link the exact pinned
    // client API 2.5.0 build this crate's FFI declarations were written
    // against (see docs/BUILD.md).
    let existing = env::var("PKG_CONFIG_PATH").unwrap_or_default();
    let combined = if existing.is_empty() {
        pkgconfig_dir.display().to_string()
    } else {
        format!("{}:{existing}", pkgconfig_dir.display())
    };
    // SAFETY: build scripts run single-threaded, before any of this crate's
    // own code; this only mutates this build-script process's environment.
    unsafe {
        env::set_var("PKG_CONFIG_PATH", &combined);
    }

    let probe = pkg_config::Config::new()
        .atleast_version("2.5.0")
        .probe("mpv");
    match probe {
        Ok(_) => {
            // `probe` already emitted the correct cargo:rustc-link-search /
            // cargo:rustc-link-lib directives from mpv.pc's `Libs:` line.
        }
        Err(err) => {
            // pkg-config crate/binary unavailable for some reason: fall back
            // to linking the vendored dylib directly by path. This still
            // requires `vendor/prefix/lib/libmpv.dylib` to exist (see
            // docs/BUILD.md / scripts/build-vendor.sh) — it only removes the
            // dependency on the `pkg-config` binary itself.
            println!(
                "cargo:warning=pkg-config probe for mpv failed ({err}); falling back to a direct \
                 -L/-lmpv link against {}",
                vendor_lib.display()
            );
            println!("cargo:rustc-link-search=native={}", vendor_lib.display());
            println!("cargo:rustc-link-lib=dylib=mpv");
        }
    }

    // Belt-and-suspenders rpath so the test/host binary finds libmpv.dylib
    // (and its own dependency chain — ffmpeg/libplacebo/libass) at runtime
    // without DYLD_LIBRARY_PATH. Not strictly load-bearing today (per
    // docs/BUILD.md, the vendored dylibs currently carry *absolute* install
    // names into vendor/prefix, which the loader resolves directly), but it
    // is once those get rewritten to @rpath for app bundling, and it's
    // harmless either way.
    println!("cargo:rustc-link-arg=-Wl,-rpath,{}", vendor_lib.display());

    // Tests headlessly render via CGL (see tests/common/gl.rs); OpenGL.framework
    // ships the desktop GL entry points directly, so we can declare and link
    // them without going through the render API's own get_proc_address path.
    let target_os = env::var("CARGO_CFG_TARGET_OS").unwrap_or_default();
    if target_os == "macos" {
        println!("cargo:rustc-link-lib=framework=OpenGL");
    }

    println!("cargo:rerun-if-env-changed=PKG_CONFIG_PATH");
    println!("cargo:rerun-if-changed=build.rs");
}
